-- Are there any records with missing values in important columns?
SELECT *
FROM ecommerce_data
WHERE product_id IS NULL
     OR category IS NULL
     OR price IS NULL
     OR discount IS NULL
     OR final_price IS NULL
     OR payment_method IS NULL
     OR purchase_date IS NULL ;
-- Are there any duplicate transactions in the dataset?
SELECT  product_id, category, purchase_date, COUNT(*) AS duplicate_count
FROM ecommerce_data
GROUP BY product_id, category, purchase_date
HAVING COUNT(*) > 1 ;
-- Are there any products with zero or negative prices?
SELECT *
FROM ecommerce_data
WHERE price <= 0 ; 
-- Are there any discounts outside the valid range (0–100%)?
SELECT discount
FROM ecommerce_data
WHERE discount < 0 OR discount > 100 ;
-- Are there any records where the final price is greater than the original price?
SELECT *
FROM ecommerce_data
WHERE final_price > price ;
-- Display all records from the dataset. 
SELECT *
FROM ecommerce_data ;
-- Show only product_id and category.
SELECT product_id, category
FROM ecommerce_data ; 
-- Find all products belonging to the Electronics category.
SELECT *
FROM ecommerce_data
WHERE category = "Electronics" ;
-- Show products where the original price is greater than ₹400.
SELECT *
FROM ecommerce_data
WHERE price > 400 ;
-- Find products having a discount greater than 20%.
SELECT *
FROM ecommerce_data
WHERE discount > 20 ; 
-- Display all purchases made using UPI.
SELECT *
FROM ecommerce_data
WHERE payment_method = "UPI" ; 
-- Show products whose final price is less than ₹100.
SELECT *
FROM ecommerce_data
WHERE final_price < 100 ; 
-- Display unique categories available in the dataset.
SELECT DISTINCT category
FROM ecommerce_data ;  
--  Sort products by original price in descending order.
SELECT *
FROM ecommerce_data
ORDER BY price DESC ;
-- Show the top 10 most expensive products based on original price.
SELECT *
FROM ecommerce_data
ORDER BY price DESC
LIMIT 10 ;
-- Find products with discounts between 10% and 30%. 
SELECT *
FROM ecommerce_data
WHERE discount BETWEEN 10 AND 30 ; 
-- Show products whose category is either Electronics or Clothing.
SELECT *
FROM ecommerce_data
WHERE category IN ("Electronics" , "Clothing") ; 
-- Find products purchased using Credit Card and having final price above ₹400.
SELECT *
FROM ecommerce_data
WHERE payment_method = "Credit Card" AND final_price > 400 ; 
-- Display purchases made after 1 July 2024.
SELECT *
FROM ecommerce_data
WHERE purchase_date > "2024-07-01" ;  
-- Find products where discount is exactly 25%.
SELECT *
FROM ecommerce_data
WHERE discount = 25 ;
-- Show products whose final price is between ₹100 and ₹300.
SELECT *
FROM ecommerce_data
WHERE final_price BETWEEN  100 AND 300 ;
-- Find all products that are not paid through UPI.
SELECT *
FROM ecommerce_data
WHERE NOT payment_method = "UPI" ; 
-- Display products purchased in November 2024.
SELECT *
FROM ecommerce_data
WHERE purchase_date >= "2024-11-01" AND purchase_date < "2024-12-01" ;
-- Show products where original price and final price differ by more than ₹100.
SELECT *
FROM ecommerce_data
WHERE ABS(price - final_price) > 100 ;  
-- Find purchases made using either Debit Card or Net Banking. 
SELECT *
FROM ecommerce_data
WHERE payment_method = "Debit Card" OR payment_method = "Net Banking" ;
-- Calculate the total sales amount. 
SELECT ROUND(SUM(final_price),2) AS  total_sales_amount
FROM ecommerce_data ;
-- Find the average original product price.
SELECT AVG(price) AS avg_price
FROM ecommerce_data ; 
-- Find the highest original price and lowest final price.
SELECT MAX(price) AS max_price, MIN(final_price) AS min_final_price
FROM ecommerce_data ; 
-- Count total purchases.
SELECT COUNT(*) AS total_purchases
FROM ecommerce_data ;
-- Count distinct categories.
SELECT COUNT(DISTINCT category) AS distinct_category
FROM ecommerce_data ;
-- Find total revenue generated through UPI payments.
SELECT ROUND(SUM(final_price),2) AS total_revenue, payment_method
FROM ecommerce_data
WHERE payment_method = "UPI" ;
-- Calculate average discount percentage.
SELECT AVG(discount) AS avg_discount
FROM ecommerce_data ; 
-- Find total revenue generated from Electronics category.
SELECT  ROUND(SUM(final_price),2) AS total_revenue, category
FROM ecommerce_data
WHERE category = "Electronics" ;
-- Calculate total discount amount given across all purchases.
SELECT ROUND(SUM(price - final_price),2) AS total_discount_amount
FROM ecommerce_data ; 
-- Count products in each category.
SELECT COUNT(*) AS total_product, category
FROM ecommerce_data
GROUP BY category ;
-- Calculate average original price for each category.
SELECT AVG(price) AS avg_price, category
FROM ecommerce_data
GROUP BY category ;
-- Find total revenue generated by each payment method. 
SELECT SUM(final_price) AS total_revenue, payment_method
FROM ecommerce_data
GROUP BY payment_method  ;
-- Find maximum original price in every category.
SELECT MAX(price) AS max_price, category
FROM ecommerce_data
GROUP BY category ;
-- Find minimum final price in each category.
SELECT MIN(final_price) AS min_final_price, category
FROM ecommerce_data
GROUP BY category ;
-- Show categories having more than 200 purchases.
SELECT category, COUNT(*) AS total_purchases
FROM ecommerce_data
GROUP BY category
HAVING COUNT(*) > 200 ;
-- Find payment methods with average purchase value greater than ₹200.
SELECT payment_method, AVG(final_price) AS avg_purchases_value
FROM ecommerce_data
GROUP BY payment_method
HAVING AVG(final_price) > 200 ;
-- Find categories where average discount exceeds 20%.
SELECT category, AVG(discount) AS avg_discount
FROM ecommerce_data
GROUP BY category 
HAVING AVG(discount) > 20 ;
-- Calculate total discount amount category-wise.           
SELECT SUM(price - final_price) AS total_discount_amount, category
FROM ecommerce_data
GROUP BY category ;  
-- Find the category generating the highest revenue. 
SELECT category, SUM(final_price) AS highest_revenue
FROM ecommerce_data 
GROUP BY category
ORDER BY highest_revenue DESC
LIMIT 1 ;
-- Create a new column called price_range:      
-- Budget (< ₹100)
-- Mid Range (₹100–₹300)
-- Upper Mid (₹301-₹400) 
-- Premium (> ₹400) 
SELECT price,
CASE
    WHEN price < 100 THEN "Budget"
    WHEN price BETWEEN 100 AND 300 THEN "Mid Range"
    WHEN price BETWEEN 301 AND 400 THEN "Upper Mid"
    ELSE "Premium"
END AS price_range
FROM ecommerce_data ;
-- Count products in each price range.
SELECT 
CASE
    WHEN price < 100 THEN "Budget"
    WHEN price BETWEEN 100 AND 300 THEN "Mid Range"
	WHEN price BETWEEN 301 AND 400 THEN "Upper Mid"
    ELSE "Premium"
END AS price_range, COUNT(*) AS total_products
FROM ecommerce_data
GROUP BY price_range;
-- Classify discounts as:
-- Low (<10%)
-- Medium (10-25%)
-- High (>25%)
-- and count products in each class
SELECT 
CASE
    WHEN discount < 10 THEN "Low"
    WHEN discount BETWEEN 10 AND 25 THEN "Medium"
    ELSE "High"
END AS dicount_class, COUNT(*) AS total_products
FROM ecommerce_data 
GROUP BY dicount_class ; 
-- Determine whether each transaction is:
-- Profitable (Final Price > ₹300)
-- Low Value (≤ ₹300) 
SELECT category,
CASE
    WHEN final_price > 300 THEN "Profitable"
    ELSE "Low Value"
END AS transaction_type
FROM ecommerce_data ;    
-- Find total revenue generated from each discount class.
SELECT 
CASE
    WHEN discount < 10 THEN "Low"
    WHEN discount BETWEEN 10 AND 25 THEN "Medium"
    ELSE "High"
END AS dicount_category, SUM(final_price) AS total_price
FROM ecommerce_data 
GROUP BY dicount_category ;
-- Find products whose original price is higher than the average original price of all products.
SELECT *
FROM ecommerce_data
WHERE price > (SELECT AVG(price) 
               FROM ecommerce_data) ;
-- Find products having the maximum discount in the dataset.
SELECT *
FROM ecommerce_data
WHERE discount = (SELECT MAX(discount) 
                  FROM ecommerce_data) ;
-- Using a CTE, calculate category-wise revenue and display only categories whose revenue
-- is above the overall average category revenue. 
WITH category_revenue AS(
       SELECT SUM(final_price) AS total_revenue, category
       FROM ecommerce_data
       GROUP BY category
       )

SELECT *
FROM category_revenue
WHERE total_revenue > (SELECT AVG(total_revenue)
                       FROM category_revenue) ;
-- Rank products within each category based on original price using: RANK()
SELECT product_id, category, price,
RANK() OVER(PARTITION BY category ORDER BY price DESC) AS product_rank
FROM ecommerce_data ;
-- For each category, show:         
-- purchase_date
-- final_price
-- and calculate a running total of revenue using: SUM() OVER() 
SELECT category, purchase_date, final_price,
SUM(final_price) OVER(PARTITION BY category ORDER BY purchase_date) AS running_revenue
FROM ecommerce_data ;
-- Find the month that generated the highest revenue.
SELECT MONTH(purchase_date) AS month, ROUND(SUM(final_price),2) AS highest_revenue 
FROM ecommerce_data
GROUP BY  MONTH(purchase_date)
ORDER BY SUM(final_price) DESC
LIMIT 1 ;
-- Find the most preferred payment method. 
SELECT payment_method, COUNT(*) AS total_transactions
FROM ecommerce_data
GROUP BY payment_method
ORDER BY COUNT(*) DESC
LIMIT 1 ;
-- Calculate category-wise contribution percentage to total revenue.
SELECT category, SUM(final_price) AS total_revenue, 
ROUND((SUM(final_price) * 100) / (SELECT SUM(final_price) FROM ecommerce_data), 2) AS contribution_percentage
FROM ecommerce_data
GROUP BY category ;
-- Find top 3 highest revenue-generating categories.
SELECT SUM(final_price) AS total_revenue, category
FROM ecommerce_data
GROUP BY category
ORDER BY SUM(final_price) DESC
LIMIT 3 ;
-- For every category, find the product having the highest discount.
SELECT category, discount, product_id
FROM (SELECT category, discount, product_id,
      DENSE_RANK() OVER(PARTITION BY category ORDER BY discount DESC) AS discount_rank
      FROM ecommerce_data) AS t
WHERE discount_rank = 1 ;
-- Monthly Revenue Trend 
SELECT MONTH(purchase_date) AS months, SUM(final_price) AS total_price
FROM ecommerce_data
GROUP BY MONTH(purchase_date)
ORDER BY months ;
-- Best Selling Category
SELECT category, COUNT(*) AS total_sales
FROM ecommerce_data
GROUP BY category
ORDER BY total_sales DESC
LIMIT 1 ; 
-- Average Discount by Payment Method
SELECT payment_method, AVG(discount) AS avg_discount
FROM ecommerce_data 
GROUP BY payment_method ;
-- Top 5 Most Expensive Products
SELECT product_id, price, category
FROM ecommerce_data
ORDER BY price DESC 
LIMIT 5 ; 
-- Revenue Rank of Categories 
SELECT category, SUM(final_price) AS revenue,
DENSE_RANK() OVER(ORDER BY SUM(final_price) DESC) AS revenue_rank
FROM ecommerce_data 
GROUP BY category ;
-- Year-Month Sales Report 
SELECT DATE_FORMAT(purchase_date,"%Y-%m") AS year_month_report , SUM(final_price) AS revenue
FROM ecommerce_data
GROUP BY year_month_report ;
-- Analyze each product category by calculating its average discount and average final selling price to understand category-wise pricing 
-- and discount strategies 
SELECT AVG(discount) AS avg_discount, AVG(final_price) AS avg_final_price, category
FROM ecommerce_data
GROUP BY category ;
-- Are there any records with missing values in important columns?
SELECT *
FROM ecommerce_data
WHERE product_id IS NULL
     OR category IS NULL
     OR price IS NULL
     OR discount IS NULL
     OR final_price IS NULL
     OR payment_method IS NULL
     OR purchase_date IS NULL ;
-- Are there any duplicate transactions in the dataset?
SELECT  product_id, category, purchase_date, COUNT(*) AS duplicate_count
FROM ecommerce_data
GROUP BY product_id, category, purchase_date
HAVING COUNT(*) > 1 ;
-- Are there any products with zero or negative prices?
SELECT *
FROM ecommerce_data
WHERE price <= 0 ; 
-- Are there any discounts outside the valid range (0–100%)?
SELECT discount
FROM ecommerce_data
WHERE discount < 0 OR discount > 100 ;
-- Are there any records where the final price is greater than the original price?
SELECT *
FROM ecommerce_data
WHERE final_price > price ;










 

